-- Generated by silver_codegen for silver.amf_signals
CREATE MATERIALIZED VIEW silver.amf_signals AS
WITH inpi_index AS (
  SELECT DISTINCT ON (lower(unaccent(denomination)))
         lower(unaccent(denomination)) AS deno_key,
         siren
  FROM silver.inpi_comptes
  WHERE denomination IS NOT NULL AND length(denomination) > 4
  ORDER BY lower(unaccent(denomination)), date_cloture DESC
),
dila AS (
  SELECT decision_id || '|dila' AS amf_signal_uid,
         'amf_dila' AS source_table,
         COALESCE(payload->>'TITRE', payload->>'PARTIE',
                  payload->>'entreprise', payload->>'denomination') AS entity_name,
         NULL::text AS siren_native,
         'sanction' AS signal_type,
         'HIGH' AS severity,
         COALESCE((payload->>'DATE_DEC')::date,
                  (payload->>'DATE_PUBLI')::date,
                  (payload->>'date_decision')::date,
                  ingested_at::date) AS date_signal,
         payload AS raw_payload
  FROM bronze.amf_dila_raw
),
geco AS (
  SELECT (payload->>'id') || '|geco' AS amf_signal_uid,
         'amf_geco' AS source_table,
         payload->>'denomination' AS entity_name,
         payload->>'siren' AS siren_native,
         'operation_listed' AS signal_type,
         'LOW' AS severity,
         COALESCE((payload->>'date_publication')::date, ingested_at::date) AS date_signal,
         payload AS raw_payload
  FROM bronze.amf_geco_raw
),
bdif AS (
  SELECT (payload->>'id') || '|bdif' AS amf_signal_uid,
         'amf_bdif' AS source_table,
         payload->>'partie' AS entity_name,
         NULL::text AS siren_native,
         COALESCE(payload->>'type', 'decision_individuelle') AS signal_type,
         CASE
           WHEN payload->>'type' ILIKE '%sanction%' THEN 'HIGH'
           WHEN payload->>'type' ILIKE '%agrément%' THEN 'LOW'
           ELSE 'MEDIUM'
         END AS severity,
         COALESCE((payload->>'date_decision')::date, ingested_at::date) AS date_signal,
         payload AS raw_payload
  FROM bronze.amf_bdif_raw
),
noires AS (
  SELECT (payload->>'id') || '|noires' AS amf_signal_uid,
         'amf_listes_noires' AS source_table,
         payload->>'denomination' AS entity_name,
         NULL::text AS siren_native,
         'liste_noire' AS signal_type,
         'HIGH' AS severity,
         COALESCE((payload->>'date_inscription')::date, ingested_at::date) AS date_signal,
         payload AS raw_payload
  FROM bronze.amf_listes_noires_raw
),
unioned AS (
  SELECT * FROM dila
  UNION ALL SELECT * FROM geco
  UNION ALL SELECT * FROM bdif
  UNION ALL SELECT * FROM noires
)
SELECT
  u.amf_signal_uid,
  u.source_table,
  u.entity_name,
  COALESCE(u.siren_native, i.siren) AS siren,
  u.signal_type,
  u.severity,
  u.date_signal,
  u.raw_payload
FROM unioned u
LEFT JOIN inpi_index i
  ON u.siren_native IS NULL
  AND i.deno_key = lower(unaccent(COALESCE(u.entity_name, '')))
  AND length(COALESCE(u.entity_name, '')) > 4
WHERE u.entity_name IS NOT NULL;

CREATE INDEX ON silver.amf_signals (siren) WHERE siren IS NOT NULL;
CREATE INDEX ON silver.amf_signals (lower(entity_name));
CREATE INDEX ON silver.amf_signals (severity);
CREATE INDEX ON silver.amf_signals (signal_type);
CREATE INDEX ON silver.amf_signals (date_signal DESC);
CREATE INDEX ON silver.amf_signals ((severity, date_signal DESC)) WHERE severity = 'HIGH';
