-- Generated by silver_codegen for silver.cnil_sanctions

CREATE MATERIALIZED VIEW silver.cnil_sanctions AS
WITH inpi_index AS (
  SELECT DISTINCT ON (lower(unaccent(denomination)))
         lower(unaccent(denomination)) AS deno_key,
         siren
  FROM silver.inpi_comptes
  WHERE denomination IS NOT NULL AND length(denomination) > 4
  ORDER BY lower(unaccent(denomination)), date_cloture DESC NULLS LAST
),
base AS (
  SELECT
    sanction_id,
    payload,
    ingested_at,
    COALESCE(payload->>'organisme', payload->>'entreprise', payload->>'nom') AS organisme,
    lower(unaccent(COALESCE(payload->>'organisme', payload->>'entreprise', payload->>'nom', ''))) AS organisme_lower,
    COALESCE(
      NULLIF(payload->>'date', '')::date,
      NULLIF(payload->>'date_decision', '')::date,
      NULLIF(payload->>'date_publication', '')::date
    ) AS date_decision,
    COALESCE(
      NULLIF(payload->>'montant_amende', '')::numeric,
      NULLIF(payload->>'amende_administrative', '')::numeric,
      NULLIF(payload->>'montant', '')::numeric,
      0::numeric
    ) AS montant_amende,
    COALESCE(payload->>'motif', payload->>'manquement', payload->>'objet') AS motif,
    COALESCE(payload->>'type_decision', payload->>'nature', 'sanction') AS type_decision
  FROM bronze.cnil_sanctions_raw
  WHERE payload IS NOT NULL
)
SELECT
  b.sanction_id,
  b.organisme,
  b.organisme_lower,
  i.siren,
  b.date_decision,
  b.montant_amende,
  b.motif,
  b.type_decision,
  CASE
    WHEN b.montant_amende >= 1000000 THEN 'critical'
    WHEN b.montant_amende >= 100000 THEN 'high'
    WHEN b.montant_amende > 0 THEN 'medium'
    ELSE 'low'
  END AS severity,
  b.payload,
  b.ingested_at
FROM base b
LEFT JOIN inpi_index i ON i.deno_key = b.organisme_lower
WHERE b.organisme IS NOT NULL
WITH NO DATA;

CREATE INDEX ON silver.cnil_sanctions (sanction_id);
CREATE INDEX ON silver.cnil_sanctions (siren) WHERE siren IS NOT NULL;
CREATE INDEX ON silver.cnil_sanctions USING gin (organisme_lower gin_trgm_ops);
CREATE INDEX ON silver.cnil_sanctions (severity);
CREATE INDEX ON silver.cnil_sanctions (date_decision DESC);
CREATE INDEX ON silver.cnil_sanctions (type_decision);
