-- Generated by silver_codegen for silver.dgccrf_sanctions
CREATE MATERIALIZED VIEW silver.dgccrf_sanctions AS
WITH inpi_index AS (
  SELECT DISTINCT ON (lower(unaccent(denomination)))
         lower(unaccent(denomination)) AS deno_key,
         siren
  FROM silver.inpi_comptes
  WHERE denomination IS NOT NULL AND length(denomination) > 4
  ORDER BY lower(unaccent(denomination)), date_cloture DESC
)
SELECT
  b.sanction_id,
  b.entreprise,
  lower(unaccent(coalesce(b.entreprise, ''))) AS entreprise_lower,
  i.siren,
  b.date_decision,
  b.montant_amende,
  b.motif,
  CASE
    WHEN b.montant_amende >= 100000 OR b.motif ILIKE '%liquidation%' THEN 'critical'
    WHEN b.montant_amende >= 10000 THEN 'high'
    WHEN b.montant_amende > 0 THEN 'medium'
    ELSE 'low'
  END AS severity,
  b.payload,
  b.ingested_at
FROM bronze.dgccrf_sanctions_raw b
LEFT JOIN inpi_index i
  ON i.deno_key = lower(unaccent(coalesce(b.entreprise, '')))
WHERE b.entreprise IS NOT NULL;

CREATE INDEX ON silver.dgccrf_sanctions (sanction_id);
CREATE INDEX ON silver.dgccrf_sanctions (siren) WHERE siren IS NOT NULL;
CREATE INDEX ON silver.dgccrf_sanctions USING gin (entreprise_lower gin_trgm_ops);
CREATE INDEX ON silver.dgccrf_sanctions (severity);
CREATE INDEX ON silver.dgccrf_sanctions (date_decision DESC);
