-- Generated by silver_codegen for silver.sanctions
CREATE MATERIALIZED VIEW silver.sanctions AS
WITH amf AS (
  SELECT
    amf_signal_uid AS sanction_uid,
    'amf'::text AS source,
    amf_signal_uid AS entity_id,
    siren,
    entity_name AS entreprise,
    lower(unaccent(coalesce(entity_name, ''))) AS entity_lower,
    date_signal AS date_decision,
    signal_type AS type_decision,
    NULL::text AS motif,
    NULL::numeric AS montant_amende,
    LOWER(severity) AS severity,
    ARRAY['amf','financier', LOWER(severity)]::text[] AS topics,
    ARRAY['fr']::text[] AS countries,
    NULL::text AS jurisdiction
  FROM silver.amf_signals
),
opensanctions AS (
  SELECT
    entity_id AS sanction_uid,
    'opensanctions'::text AS source,
    entity_id,
    unnest(CASE
      WHEN sirens_fr IS NULL OR array_length(sirens_fr, 1) IS NULL THEN ARRAY[NULL::text]
      ELSE sirens_fr
    END)::char(9) AS siren,
    caption AS entreprise,
    name_lower AS entity_lower,
    first_seen::date AS date_decision,
    schema AS type_decision,
    array_to_string(topics, ', ') AS motif,
    NULL::numeric AS montant_amende,
    CASE
      WHEN topics @> ARRAY['sanction'] THEN 'critical'
      WHEN topics @> ARRAY['sanction.linked'] THEN 'high'
      WHEN topics @> ARRAY['crime'] THEN 'critical'
      WHEN topics @> ARRAY['pep'] THEN 'high'
      WHEN topics @> ARRAY['reg.warn'] THEN 'medium'
      ELSE 'low'
    END AS severity,
    topics,
    countries,
    NULL::text AS jurisdiction
  FROM silver.opensanctions
),
icij AS (
  SELECT
    match_uid AS sanction_uid,
    'icij'::text AS source,
    icij_entity_id AS entity_id,
    NULL::char(9) AS siren,
    icij_entity_name AS entreprise,
    lower(unaccent(coalesce(icij_entity_name, ''))) AS entity_lower,
    NULL::date AS date_decision,
    icij_database AS type_decision,
    'offshore_leak'::text AS motif,
    NULL::numeric AS montant_amende,
    CASE match_confidence
      WHEN 'HIGH' THEN 'high'
      WHEN 'MEDIUM' THEN 'medium'
      ELSE 'low'
    END AS severity,
    ARRAY['icij','offshore', icij_database]::text[] AS topics,
    ARRAY[lower(jurisdiction)]::text[] AS countries,
    jurisdiction
  FROM silver.icij_offshore_match
),
dgccrf AS (
  SELECT
    sanction_id AS sanction_uid,
    'dgccrf'::text AS source,
    sanction_id AS entity_id,
    siren,
    entreprise,
    entreprise_lower AS entity_lower,
    date_decision,
    'sanction'::text AS type_decision,
    motif,
    montant_amende,
    severity,
    ARRAY['dgccrf','concurrence', severity]::text[] AS topics,
    ARRAY['fr']::text[] AS countries,
    NULL::text AS jurisdiction
  FROM silver.dgccrf_sanctions
),
cnil AS (
  SELECT
    sanction_id AS sanction_uid,
    'cnil'::text AS source,
    sanction_id AS entity_id,
    siren,
    organisme AS entreprise,
    organisme_lower AS entity_lower,
    date_decision,
    type_decision,
    motif,
    montant_amende,
    severity,
    ARRAY['cnil','rgpd', severity]::text[] AS topics,
    ARRAY['fr']::text[] AS countries,
    NULL::text AS jurisdiction
  FROM silver.cnil_sanctions
)
SELECT * FROM amf
UNION ALL SELECT * FROM opensanctions
UNION ALL SELECT * FROM icij
UNION ALL SELECT * FROM dgccrf
UNION ALL SELECT * FROM cnil
WITH NO DATA;

CREATE INDEX ON silver.sanctions (sanction_uid);
CREATE INDEX ON silver.sanctions ((siren)) WHERE siren IS NOT NULL;
CREATE INDEX ON silver.sanctions (source);
CREATE INDEX ON silver.sanctions USING gin (entity_lower gin_trgm_ops);
CREATE INDEX ON silver.sanctions (severity);
CREATE INDEX ON silver.sanctions USING gin (topics);
CREATE INDEX ON silver.sanctions (date_decision DESC);
