"""Unit tests for silver_codegen — covers the pure functions whose regressions
caused the duplicate-index / never-bootstrapped MV bugs.

These tests run without Postgres or Ollama (see conftest stubs).
"""
from __future__ import annotations

import re

import pytest

from ingestion import silver_codegen as sc


# ─────────────────────────────────────────────────────────────────────────────
# _validate_sql
# ─────────────────────────────────────────────────────────────────────────────

VALID_SQL = (
    "-- Generated by silver_codegen for silver.foo\n"
    "CREATE MATERIALIZED VIEW silver.foo AS\n"
    "SELECT id FROM bronze.bar;\n"
    "CREATE INDEX ON silver.foo (id);\n"
)


def test_validate_sql_accepts_plain_create():
    ok, msg = sc._validate_sql(VALID_SQL)
    assert ok, msg


def test_validate_sql_rejects_if_not_exists():
    """IF NOT EXISTS makes _apply_sql's CREATE silently no-op on regen,
    which is the root cause of the 17 duplicate indexes on insee_unites_legales."""
    sql = VALID_SQL.replace(
        "CREATE MATERIALIZED VIEW silver.foo",
        "CREATE MATERIALIZED VIEW IF NOT EXISTS silver.foo",
    )
    ok, msg = sc._validate_sql(sql)
    assert not ok
    assert "IF NOT EXISTS" in msg


def test_validate_sql_rejects_or_replace():
    """Postgres has no CREATE OR REPLACE MATERIALIZED VIEW — this would error
    at execute time and leave the silver in a broken state."""
    sql = VALID_SQL.replace(
        "CREATE MATERIALIZED VIEW silver.foo",
        "CREATE OR REPLACE MATERIALIZED VIEW silver.foo",
    )
    ok, msg = sc._validate_sql(sql)
    assert not ok
    assert "OR REPLACE" in msg


def test_validate_sql_rejects_drop_bronze():
    sql = VALID_SQL + "\nDROP TABLE bronze.bar;\n"
    ok, msg = sc._validate_sql(sql)
    assert not ok
    assert "Banned" in msg


def test_validate_sql_rejects_no_silver_target():
    sql = "CREATE MATERIALIZED VIEW public.foo AS SELECT 1 FROM bronze.bar;"
    ok, msg = sc._validate_sql(sql)
    assert not ok
    assert "MATERIALIZED VIEW silver." in msg


def test_validate_sql_accepts_silver_only_source():
    """silver-of-silver (e.g. silver.entreprises_signals) reads from other
    silvers — bronze isn't required as long as a silver source is present."""
    sql = (
        "CREATE MATERIALIZED VIEW silver.derived AS\n"
        "SELECT siren FROM silver.inpi_dirigeants;\n"
    )
    ok, msg = sc._validate_sql(sql)
    assert ok, msg


def test_validate_sql_rejects_no_source():
    sql = "CREATE MATERIALIZED VIEW silver.empty AS SELECT 1 AS x;"
    ok, msg = sc._validate_sql(sql)
    assert not ok
    assert "source" in msg.lower()


def test_validate_sql_rejects_dangerous_grant():
    sql = VALID_SQL + "\nGRANT ALL ON SCHEMA silver TO PUBLIC;\n"
    ok, msg = sc._validate_sql(sql)
    assert not ok


# ─────────────────────────────────────────────────────────────────────────────
# _topo_sort_specs
# ─────────────────────────────────────────────────────────────────────────────

def test_topo_sort_silver_of_silver_after_deps(tmp_path, monkeypatch):
    """A silver that lists another silver as source must appear AFTER it."""
    specs_dir = tmp_path / "silver_specs"
    specs_dir.mkdir()
    (specs_dir / "a_pure_bronze.yaml").write_text(
        "silver_name: silver.a_pure_bronze\nsource_tables:\n  - bronze.x\n",
        encoding="utf-8",
    )
    (specs_dir / "b_uses_a.yaml").write_text(
        "silver_name: silver.b_uses_a\n"
        "source_tables:\n"
        "  - bronze.y\n"
        "  - silver.a_pure_bronze\n",
        encoding="utf-8",
    )
    (specs_dir / "_skipme.yaml").write_text("silver_name: silver.skip\n", encoding="utf-8")

    monkeypatch.setattr(sc, "SILVER_SPECS_DIR", specs_dir)
    ordered = sc._topo_sort_specs()

    assert "silver.a_pure_bronze" in ordered
    assert "silver.b_uses_a" in ordered
    assert ordered.index("silver.a_pure_bronze") < ordered.index("silver.b_uses_a")
    assert "silver.skip" not in ordered


def test_topo_sort_handles_diamond(tmp_path, monkeypatch):
    """Diamond: D depends on B and C; B and C both depend on A. Order: A, then B/C, then D."""
    specs_dir = tmp_path / "silver_specs"
    specs_dir.mkdir()
    for name, deps in [
        ("a", []),
        ("b", ["silver.a"]),
        ("c", ["silver.a"]),
        ("d", ["silver.b", "silver.c"]),
    ]:
        body = f"silver_name: silver.{name}\nsource_tables:\n  - bronze.src\n"
        for d in deps:
            body += f"  - {d}\n"
        (specs_dir / f"{name}.yaml").write_text(body, encoding="utf-8")

    monkeypatch.setattr(sc, "SILVER_SPECS_DIR", specs_dir)
    ordered = sc._topo_sort_specs()

    pos = {n: i for i, n in enumerate(ordered)}
    assert pos["silver.a"] < pos["silver.b"] < pos["silver.d"]
    assert pos["silver.a"] < pos["silver.c"] < pos["silver.d"]


def test_topo_sort_pure_bronze_alphabetical(tmp_path, monkeypatch):
    specs_dir = tmp_path / "silver_specs"
    specs_dir.mkdir()
    for n in ("zebra", "apple", "mango"):
        (specs_dir / f"{n}.yaml").write_text(
            f"silver_name: silver.{n}\nsource_tables:\n  - bronze.x\n",
            encoding="utf-8",
        )
    monkeypatch.setattr(sc, "SILVER_SPECS_DIR", specs_dir)
    assert sc._topo_sort_specs() == ["silver.apple", "silver.mango", "silver.zebra"]


# ─────────────────────────────────────────────────────────────────────────────
# _topo_levels_specs — used to parallelize bootstrap by topological level
# ─────────────────────────────────────────────────────────────────────────────

def test_topo_levels_pure_bronze_single_level(tmp_path, monkeypatch):
    """Trois silvers indépendants → un seul niveau, ordre alphabétique."""
    specs_dir = tmp_path / "silver_specs"
    specs_dir.mkdir()
    for n in ("zebra", "apple", "mango"):
        (specs_dir / f"{n}.yaml").write_text(
            f"silver_name: silver.{n}\nsource_tables:\n  - bronze.x\n",
            encoding="utf-8",
        )
    monkeypatch.setattr(sc, "SILVER_SPECS_DIR", specs_dir)
    levels = sc._topo_levels_specs()
    assert levels == [["silver.apple", "silver.mango", "silver.zebra"]]


def test_topo_levels_diamond_three_levels(tmp_path, monkeypatch):
    """Diamond: D dépend de B+C, B+C dépendent de A → 3 niveaux : [A], [B,C], [D]."""
    specs_dir = tmp_path / "silver_specs"
    specs_dir.mkdir()
    for name, deps in [
        ("a", []),
        ("b", ["silver.a"]),
        ("c", ["silver.a"]),
        ("d", ["silver.b", "silver.c"]),
    ]:
        body = f"silver_name: silver.{name}\nsource_tables:\n  - bronze.src\n"
        for d in deps:
            body += f"  - {d}\n"
        (specs_dir / f"{name}.yaml").write_text(body, encoding="utf-8")
    monkeypatch.setattr(sc, "SILVER_SPECS_DIR", specs_dir)
    levels = sc._topo_levels_specs()
    assert levels == [
        ["silver.a"],
        ["silver.b", "silver.c"],
        ["silver.d"],
    ]


def test_topo_levels_silver_of_silver_two_levels(tmp_path, monkeypatch):
    """B dépend de A → niveaux [A] puis [B]. Skip _underscore."""
    specs_dir = tmp_path / "silver_specs"
    specs_dir.mkdir()
    (specs_dir / "a_pure.yaml").write_text(
        "silver_name: silver.a_pure\nsource_tables:\n  - bronze.x\n",
        encoding="utf-8",
    )
    (specs_dir / "b_uses_a.yaml").write_text(
        "silver_name: silver.b_uses_a\n"
        "source_tables:\n  - bronze.y\n  - silver.a_pure\n",
        encoding="utf-8",
    )
    (specs_dir / "_skipme.yaml").write_text("silver_name: silver.skip\n", encoding="utf-8")
    monkeypatch.setattr(sc, "SILVER_SPECS_DIR", specs_dir)
    levels = sc._topo_levels_specs()
    assert levels == [["silver.a_pure"], ["silver.b_uses_a"]]
    flat = [n for lv in levels for n in lv]
    assert "silver.skip" not in flat


def test_topo_levels_flat_matches_topo_sort(tmp_path, monkeypatch):
    """`_topo_sort_specs` doit être l'aplatissement de `_topo_levels_specs`."""
    specs_dir = tmp_path / "silver_specs"
    specs_dir.mkdir()
    for name, deps in [
        ("alpha", []),
        ("beta", ["silver.alpha"]),
        ("gamma", []),
        ("delta", ["silver.beta", "silver.gamma"]),
    ]:
        body = f"silver_name: silver.{name}\nsource_tables:\n  - bronze.src\n"
        for d in deps:
            body += f"  - {d}\n"
        (specs_dir / f"{name}.yaml").write_text(body, encoding="utf-8")
    monkeypatch.setattr(sc, "SILVER_SPECS_DIR", specs_dir)
    flat = [n for lv in sc._topo_levels_specs() for n in lv]
    assert flat == sc._topo_sort_specs()


def test_topo_levels_real_repo_structure():
    """Les specs réelles du repo doivent produire au moins 2 niveaux
    (entreprises_signals est silver-of-silver donc level >= 1)."""
    levels = sc._topo_levels_specs()
    assert len(levels) >= 1
    flat = [n for lv in levels for n in lv]
    # Si entreprises_signals est dans le repo, il doit être à un niveau >= 1
    if "silver.entreprises_signals" in flat:
        for lv_idx, lv in enumerate(levels):
            if "silver.entreprises_signals" in lv:
                assert lv_idx >= 1, "entreprises_signals doit être après ses deps"
                break


# ─────────────────────────────────────────────────────────────────────────────
# Real specs sanity (catches malformed YAML / wrong source schema in repo)
# ─────────────────────────────────────────────────────────────────────────────

def test_repo_specs_topo_sort_runs():
    """Sanity: the production silver_specs/ directory must produce a valid order
    and entreprises_signals (silver-of-silver) must come last among loaded specs."""
    ordered = sc._topo_sort_specs()
    assert len(ordered) >= 14, f"expected >= 14 specs, got {len(ordered)}: {ordered}"
    # Expected pure-bronze specs that entreprises_signals reads — must precede it.
    if "silver.entreprises_signals" in ordered:
        idx_signals = ordered.index("silver.entreprises_signals")
        for dep in ("silver.bodacc_annonces", "silver.cession_events",
                    "silver.judilibre_decisions", "silver.opensanctions",
                    "silver.osint_companies_enriched", "silver.press_mentions_matched",
                    "silver.inpi_comptes", "silver.inpi_dirigeants"):
            if dep in ordered:
                assert ordered.index(dep) < idx_signals, f"{dep} must precede entreprises_signals"


# ─────────────────────────────────────────────────────────────────────────────
# _extract_sql_from_response
# ─────────────────────────────────────────────────────────────────────────────

def test_extract_sql_from_fenced_block():
    raw = "Voici le SQL:\n```sql\nCREATE MATERIALIZED VIEW silver.x AS SELECT 1;\n```\nFin."
    sql = sc._extract_sql_from_response(raw)
    assert sql is not None
    assert sql.startswith("CREATE")


def test_extract_sql_from_bare_create():
    raw = "CREATE MATERIALIZED VIEW silver.x AS SELECT 1 FROM bronze.y;"
    assert sc._extract_sql_from_response(raw) == raw


def test_extract_sql_returns_none_for_chatter():
    raw = "Désolé, je ne peux pas générer ce SQL."
    assert sc._extract_sql_from_response(raw) is None
